### ISSUE TITLE
Task one - role for first milestone

### ISSUE THREAD

**Issue by shaw0106** [sagehartly/simple-chat-app#4]
Role: Lead

 - [x] Create flow chart
- [x] Sketch low fed wireframe
- [x] Meet to discuss options, Monday Jan 26th 

@ericadamski
